// app/api/factcheck/route.js
// Runs the Fact-Check Agent on a candidate learning and stores it in the
// pending review queue. NOTHING here writes to approvedLearnings — that only
// happens via an explicit PATCH to /api/learnings from the operator.

import { auth } from "@clerk/nextjs/server";
import { FACT_CHECK_SYSTEM_PROMPT } from "../../../lib/prompts";
import { callAgent } from "../../../lib/anthropic";
import { addPending } from "../../../lib/storage";

export const runtime = "nodejs";
export const maxDuration = 30;

export async function POST(req) {
  const { userId } = await auth();
  if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { candidateLearning, sourceQuestion } = await req.json();
    if (!candidateLearning) {
      return Response.json({ error: "Missing candidateLearning." }, { status: 400 });
    }

    const userMsg = `CANDIDATE LEARNING (generated by the Meta-Reviewer, unverified):\n"${candidateLearning}"\n\nCONTEXT — the question that produced it: ${sourceQuestion}\n\nAudit this candidate learning per your instructions.`;

    let verdict;
    try {
      const raw = await callAgent(FACT_CHECK_SYSTEM_PROMPT, userMsg, true);
      const cleaned = raw.replace(/```json|```/g, "").trim();
      verdict = JSON.parse(cleaned);
    } catch (e) {
      verdict = {
        verdict: "needs_hedging",
        confidence: "low",
        concerns: [`Fact-check agent failed or returned unparsable output: ${e.message}`],
        fabricated_precision: [],
        qualitative_core_holds: null,
        suggested_rewrite: candidateLearning,
        reasoning: "Fact-check call failed — manual review required.",
      };
    }

    const pendingItem = {
      id: "p" + Date.now() + Math.random().toString(36).slice(2, 6),
      ts: Date.now(),
      raw: candidateLearning,
      sourceQuestion,
      status: "pending",
      factCheck: verdict,
    };

    await addPending(pendingItem);

    return Response.json({ item: pendingItem });
  } catch (err) {
    return Response.json({ error: err.message || "Fact-check failed." }, { status: 500 });
  }
}
